obstacle_range: 2.5
raytrace_range: 3.0

footprint: [[-0.225, -0.225], [-0.225, 0.225], [0.225, 0.225], [0.225, -0.225]]
transform_tolerance: 1
controller_patience: 2.0

static_layer:
  enabled: true
  map_topic: /rtabmap/grid_map
  unknown_cost: 255
  mark_unknown: true

obstacle_layer:
  enabled: true  
  observation_sources: laser_scan point_cloud
  observation_persistence: 0.0

  laser_scan: 
    data_type: LaserScan
    topic: scan
    marking: true
    clearing: true
    inf_is_valid: false
    min_obstacle_height: 0.2
    max_obstacle_height: 3.0

  point_cloud:
    data_type: PointCloud2
    topic: camera/depth/color/points
    marking: true
    clearing: true
    min_obstacle_height: 1.0
    max_obstacle_height: 1.5
  

voxel_layer:
  enabled: true
  origin_z: 0.0
  z_resolution: 0.1
  z_voxels: 10
  mark_threshold: 0
  observation_sources: point_cloud

  point_cloud:
    data_type: PointCloud2
    topic: rtabmap/cloud_obstacles
    marking: true
    clearing: true
    min_obstacle_height: 0.5
    max_obstacle_height: 1.0

inflation_layer:
  inflation_radius: 0.32
  cost_scaling_factor: 15.0