global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 4.0
  publish_frequency: 2.0
  resolution: 0.1
  static_map: true
  clearing_rotation_allowed: true
  clearing_rotation_distance: 0.0

  plugins:
    - name: static_layer
      type: "costmap_2d::StaticLayer"
    - name: inflation_layer
      type: "costmap_2d::InflationLayer"
    - name: obstacle_layer
      type: "costmap_2d::ObstacleLayer"