local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 4.0
  publish_frequency: 2.0

  static_map: false
  width: 5.0
  height: 5.0
  resolution: 0.1
  rolling_window: true
  clearing_rotation_allowed: true
  clearing_rotation_distance: 0.5

  plugins:
    - name: obstacle_layer
      type: "costmap_2d::ObstacleLayer"
    - name: inflation_layer
      type: "costmap_2d::InflationLayer"
#    - name: voxel_layer
#      type: "costmap_2d::VoxelLayer"
