# Move base parameters
move_base:
  controller_frequency: 20.0
  planner_patience: 5.0
  controller_patience: 2.0
  oscillation_timeout: 10.0
  oscillation_distance: 0.5

  planner:
    base_global_planner: "global_planner/GlobalPlanner"
    base_local_planner: "teb_local_planner/TebLocalPlannerROS"